<a href="https://colab.research.google.com/github/merttezcan/fakenews-twitter/blob/main/fakenews_twitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install dgl -f https://data.dgl.ai/wheels/repo.html

Looking in links: https://data.dgl.ai/wheels/repo.html
     |████████████████████████████████| 5.5 MB 2.6 MB/s 


In [4]:
import pandas as pd
import numpy as np
import dgl
import torch as th

In [5]:
#loading the nodes and features, replacing ids with new consecutive ids starting from zero.
#also doing some preprocessing

nodes_data = pd.read_csv('gilani-2017-features.csv')
nodes_data.rename(columns={'id': 'tw_id'}, inplace=True)
nodes_data.insert(0, 'new_id', range(0, 0 + len(nodes_data)))
nodes_data.drop(['name','screen_name','url','lang','time_zone','location','default_profile',
                           'default_profile_image','geo_enabled','profile_image_url','profile_use_background_image',
                           'profile_background_image_url_https','profile_text_color','profile_image_url_https',
                           'profile_sidebar_border_color','profile_background_tile','profile_sidebar_fill_color',
                           'profile_background_image_url','profile_background_color','profile_link_color','utc_offset',
                           'description','created_at'], axis=1, inplace=True)

nodes_data.replace({'class': {'human': True, 'bot': False}}, inplace=True)

display(nodes_data)

new_id  class  ...  contributors_enabled  following
0          0  False  ...                 False      False
1          1  False  ...                 False      False
2          2  False  ...                 False      False
3          3  False  ...                 False      False
4          4  False  ...                 False      False
...      ...    ...  ...                   ...        ...
2413    2413   True  ...                 False      False
2414    2414   True  ...                 False      False
2415    2415   True  ...                 False      False
2416    2416   True  ...                 False      False
2417    2417   True  ...                 False      False

[2418 rows x 15 columns]

In [6]:
#creating a small df to have tw_id and new_id, then converting it to a dictionary

df= nodes_data[['tw_id', 'new_id']]
df = df.astype('int64')
id_dict = dict(df.values)

In [7]:
#checking our dict

print(id_dict)

{461277906: 0, 808280162: 1, 1575510320: 2, 2449235599: 3, 1113769100: 4, 973224960: 5, 194908659: 6, 17187236: 7, 456177793: 8, 92985467: 9, 1375507088: 10, 466573221: 11, 1587974648: 12, 538949379: 13, 1499232864: 14, 527506722: 15, 29820945: 16, 892792496: 17, 223116969: 18, 218697713: 19, 547977614: 20, 73725383: 21, 55432787: 22, 2257879993: 23, 4307623643: 24, 59329469: 25, 581662807: 26, 224084191: 27, 1243573092: 28, 1701373465: 29, 3151691953: 30, 1401891498: 31, 877565375554215936: 32, 1570434660: 33, 2869378818: 34, 3476878998: 35, 575704180: 36, 844779426260791296: 37, 1068343760: 38, 14897840: 39, 218488955: 40, 44446850: 41, 183948528: 42, 562540682: 43, 321000402: 44, 3023174739: 45, 373490841: 46, 590316679: 47, 2222126594: 48, 178118507: 49, 96198639: 50, 2438311802: 51, 30618215: 52, 49536214: 53, 513112719: 54, 19622847: 55, 927351564: 56, 791202642043269120: 57, 1367759732: 58, 144666448: 59, 251967200: 60, 244628228: 61, 119166791: 62, 610628629: 63, 636533974: 64,

In [8]:
#loading the friends file that contains user id and friend id

edges_data = pd.read_csv("friends.csv",names=['user_id', 'friend_id'])
edges_data.dropna(inplace=True)

edges_data = edges_data.astype('int64')

print(edges_data)

           user_id            friend_id
0        461277906  1093701661292355584
1        461277906           2250033132
2        461277906            124955314
3        461277906   931101388716650496
4        461277906           1113629671
...            ...                  ...
1483155  150711216            120977182
1483156  150711216             44652080
1483157  150711216             92344997
1483158  150711216             66930860
1483159  150711216            109771764

[1482748 rows x 2 columns]


In [9]:
#using the dict that we created before, matching the ids with the new ones

edges_data['fr_source'] = edges_data['user_id'].map(id_dict)
edges_data['fr_target'] = edges_data['friend_id'].map(id_dict)


display(edges_data)

user_id            friend_id  fr_source  fr_target
0        461277906  1093701661292355584        0.0        NaN
1        461277906           2250033132        0.0        NaN
2        461277906            124955314        0.0        NaN
3        461277906   931101388716650496        0.0        NaN
4        461277906           1113629671        0.0        NaN
...            ...                  ...        ...        ...
1483155  150711216            120977182     2417.0        NaN
1483156  150711216             44652080     2417.0        NaN
1483157  150711216             92344997     2417.0        NaN
1483158  150711216             66930860     2417.0        NaN
1483159  150711216            109771764     2417.0        NaN

[1482748 rows x 4 columns]

In [10]:
#dropping the null values, that means we are removing the users that are not connected to each other

fr_edges_df = edges_data.dropna()
fr_edges_df = fr_edges_df.astype('int64')

In [11]:
display(fr_edges_df)

user_id  friend_id  fr_source  fr_target
3726     973224960  777983107          5       2256
3936     973224960  111809956          5        394
4075     973224960  355784391          5        818
4102     973224960   19478383          5       2088
4371     194908659   50393960          6       1542
...            ...        ...        ...        ...
1480977  134164413  171337448       2415       2209
1482832  150711216  116611790       2417       2218
1482945  150711216  135236273       2417       2219
1483092  150711216   78039816       2417        861
1483127  150711216   33884545       2417        443

[7809 rows x 4 columns]

In [12]:
#doing same process for the followers file

edges_data2 = pd.read_csv("followers.csv",names=['user_id', 'follower_id'])
edges_data2.dropna(inplace=True)

edges_data2 = edges_data2.astype('int64')

print(edges_data2)

           user_id          follower_id
0        461277906  1363871922677706752
1        461277906  1359030742030848000
2        461277906           1116957792
3        461277906  1363863589677801472
4        461277906           1492422193
...            ...                  ...
2147336  150711216           2351018816
2147337  150711216  1166382282019618816
2147338  150711216  1213583487162208256
2147339  150711216  1163515847358451712
2147340  150711216            594134386

[2146803 rows x 2 columns]


In [13]:
edges_data2['fw_source'] = edges_data2['user_id'].map(id_dict)
edges_data2['fw_target'] = edges_data2['follower_id'].map(id_dict)


display(edges_data2)

user_id          follower_id  fw_source  fw_target
0        461277906  1363871922677706752        0.0        NaN
1        461277906  1359030742030848000        0.0        NaN
2        461277906           1116957792        0.0        NaN
3        461277906  1363863589677801472        0.0        NaN
4        461277906           1492422193        0.0        NaN
...            ...                  ...        ...        ...
2147336  150711216           2351018816     2417.0        NaN
2147337  150711216  1166382282019618816     2417.0        NaN
2147338  150711216  1213583487162208256     2417.0        NaN
2147339  150711216  1163515847358451712     2417.0        NaN
2147340  150711216            594134386     2417.0        NaN

[2146803 rows x 4 columns]

In [14]:
fw_edges_df = edges_data2.dropna()
fw_edges_df = fw_edges_df.astype('int64')

In [15]:
display(fw_edges_df)

user_id  follower_id  fw_source  fw_target
3011     1113769100   2363987964          4        645
18255     218697713     15040988         19        976
20434      73725383    547977614         21         20
30592    1570434660    506437283         33       1877
30838    1570434660    759460784         33       2386
...             ...          ...        ...        ...
1992115   777983107    491090439       2256       1004
2027143   107930490     15485441       2292       1554
2040987   162173169    148753334       2306       1103
2091236   262749118     22411342       2360        920
2108686  2943284364     80413939       2378       2094

[533 rows x 4 columns]

In [16]:
# Create an empty list
fr_list =[]

# Iterate over each row
for rows in fr_edges_df.itertuples():
	# Create list for the current row
	my_list =[rows.fr_source, rows.fr_target]
	
	# append the list to the final list
	fr_list.append(my_list)

# Print the list
print(fr_list)

[[5, 2256], [5, 394], [5, 818], [5, 2088], [6, 1542], [6, 440], [7, 446], [8, 2358], [11, 449], [11, 1105], [12, 866], [12, 1533], [12, 1370], [13, 442], [13, 450], [13, 462], [16, 440], [16, 453], [16, 441], [16, 1544], [17, 937], [19, 177], [19, 2167], [19, 1538], [22, 2245], [26, 443], [26, 1543], [26, 182], [26, 995], [26, 1542], [26, 2382], [26, 2206], [28, 906], [28, 1105], [28, 445], [28, 1036], [32, 2271], [32, 2162], [32, 194], [33, 825], [33, 1418], [33, 872], [33, 908], [33, 2162], [33, 438], [33, 439], [39, 452], [39, 444], [39, 2123], [39, 442], [39, 925], [39, 461], [39, 1713], [39, 441], [39, 1541], [39, 62], [39, 462], [40, 1256], [41, 1541], [41, 450], [41, 452], [41, 440], [41, 462], [41, 441], [42, 1559], [42, 1557], [42, 1545], [42, 2131], [44, 1321], [44, 2327], [45, 83], [45, 936], [45, 1147], [45, 1086], [45, 2209], [45, 2177], [45, 2100], [45, 1476], [45, 1095], [46, 936], [46, 192], [46, 1561], [46, 1559], [46, 1557], [46, 853], [46, 457], [46, 453], [46, 47], 

In [17]:
# Create an empty list
fw_list =[]

# Iterate over each row
for rows in fw_edges_df.itertuples():
	# Create list for the current row
	my_list =[rows.fw_source, rows.fw_target]
	
	# append the list to the final list
	fw_list.append(my_list)

# Print the list
print(fw_list)

[[4, 645], [19, 976], [21, 20], [33, 1877], [33, 2386], [33, 1004], [49, 2209], [51, 256], [51, 254], [67, 2094], [71, 2209], [80, 296], [89, 1554], [93, 114], [117, 284], [142, 2209], [142, 379], [166, 2238], [175, 259], [177, 19], [180, 2209], [181, 920], [185, 393], [188, 2137], [205, 2209], [210, 2144], [214, 2094], [216, 995], [237, 2393], [244, 2177], [249, 1004], [258, 2209], [258, 995], [258, 2], [280, 1328], [296, 114], [297, 995], [322, 1050], [324, 920], [338, 259], [341, 920], [365, 2209], [368, 498], [379, 2209], [379, 142], [402, 397], [406, 296], [408, 2209], [408, 259], [463, 960], [465, 1059], [466, 938], [470, 2209], [470, 1213], [470, 2360], [471, 960], [472, 995], [472, 2], [472, 1324], [476, 2279], [476, 277], [476, 1399], [477, 995], [486, 2089], [490, 2041], [490, 659], [492, 1241], [492, 995], [492, 1004], [492, 258], [501, 66], [501, 960], [505, 964], [505, 938], [506, 938], [506, 336], [507, 365], [510, 1161], [517, 155], [517, 847], [520, 2396], [520, 826], [

In [18]:
#creating an heterograph with using our edge lists

g = dgl.heterograph(
    {('user', 'friend', 'user'): fr_list,
     ('user', 'follow', 'user'): fw_list
     })
g

Graph(num_nodes={'user': 2418},
      num_edges={('user', 'follow', 'user'): 533, ('user', 'friend', 'user'): 7809},
      metagraph=[('user', 'user', 'follow'), ('user', 'user', 'friend')])

In [19]:
g['friend'].edges()

(tensor([   5,    5,    5,  ..., 2417, 2417, 2417]),
 tensor([2256,  394,  818,  ..., 2219,  861,  443]))

In [20]:
#a function for creating tensors for features easily

def tensorCreator(df):

  i = 1

  for column in df.columns[1:]:
    globals()["t"+ str(i)] = th.tensor(df[column].values)
    i += 1

tensorCreator(nodes_data)   

In [21]:
#adding the tensors to the graph

g.ndata['class'] = t1
g.ndata['tw_id'] = t2
g.ndata['statuses_count'] = t3
g.ndata['followers_count'] = t4
g.ndata['friends_count'] = t5
g.ndata['favourites_count'] = t6
g.ndata['listed_count'] = t7
g.ndata['is_translator'] = t8
g.ndata['follow_request_sent'] = t9
g.ndata['protected'] = t10
g.ndata['verified'] = t11
g.ndata['notifications'] = t12
g.ndata['contributors_enabled'] = t13
g.ndata['following'] = t14

In [22]:
#done! we can check all of the nodes' features. for example:
g.nodes[2400]

NodeSpace(data={'class': tensor([True]), 'tw_id': tensor([282006208]), 'statuses_count': tensor([25336]), 'followers_count': tensor([3663561]), 'friends_count': tensor([638]), 'favourites_count': tensor([111]), 'listed_count': tensor([1185]), 'is_translator': tensor([False]), 'follow_request_sent': tensor([False]), 'protected': tensor([False]), 'verified': tensor([True]), 'notifications': tensor([False]), 'contributors_enabled': tensor([False]), 'following': tensor([False])})

In [23]:
!pip install node2vec

  Created wheel for node2vec: filename=node2vec-0.4.3-py3-none-any.whl size=5978 sha256=df63ef20285dc6faf7a87907a49151b4e02f8dfd235622cbb3549e16e651aace
  Stored in directory: /root/.cache/pip/wheels/07/62/78/5202cb8c03cbf1593b48a8a442fca8ceec2a8c80e22318bae9
Successfully built node2vec


In [24]:
import networkx as nx
from node2vec import Node2Vec

In [25]:
KGF = nx.Graph(fr_list)

In [26]:
KGF.number_of_nodes(), KGF.number_of_edges()

(1764, 7314)

In [27]:
KGFol = nx.Graph(fw_list)

In [28]:
KGFol.number_of_nodes(), KGFol.number_of_edges()

(532, 522)

In [29]:
node2vec = Node2Vec(KGF, dimensions=32, walk_length=30, num_walks=200, workers=4)

Computing transition probabilities:   0%|          | 0/1764 [00:00<?, ?it/s]

In [30]:
model = node2vec.fit(window=10, min_count=1, batch_words=4)

In [31]:
node2vec_fw = Node2Vec(KGFol, dimensions=32, walk_length=30, num_walks=200, workers=4)

Computing transition probabilities:   0%|          | 0/532 [00:00<?, ?it/s]

In [32]:
model_fw = node2vec_fw.fit(window=10, min_count=1, batch_words=4)

In [33]:
arr = []
arr2 = []
for i in range(0, KGF.number_of_nodes()):
  arr.append(model.wv.vectors[i])
  arr2.append(i)

In [34]:
n_dict = dict(zip(arr2, arr))

In [35]:
print(len(n_dict))

1764


In [36]:
#check
print(model.wv.vectors[7])
print(n_dict[7])

[ 0.07906826 -0.16399223  0.06040652 -0.09636401  0.14311644 -0.4989346
  0.46026725  0.4372431  -0.02379883 -0.16923895 -0.00941227 -0.31730112
 -0.04579119 -0.01536021  0.30664122 -0.23522836 -0.08835968  0.14635283
 -0.6472149  -0.39647296  0.06061589 -0.20517573 -0.1996076  -0.07191047
 -0.4191811   0.13527091  0.08147043 -0.15008108 -0.4261992  -0.46359593
 -0.159444   -0.2019969 ]
[ 0.07906826 -0.16399223  0.06040652 -0.09636401  0.14311644 -0.4989346
  0.46026725  0.4372431  -0.02379883 -0.16923895 -0.00941227 -0.31730112
 -0.04579119 -0.01536021  0.30664122 -0.23522836 -0.08835968  0.14635283
 -0.6472149  -0.39647296  0.06061589 -0.20517573 -0.1996076  -0.07191047
 -0.4191811   0.13527091  0.08147043 -0.15008108 -0.4261992  -0.46359593
 -0.159444   -0.2019969 ]


In [37]:
fw_arr = []
fw_arr2 = []
for i in range(0, KGFol.number_of_nodes()):
    fw_arr.append(model_fw.wv.vectors[i])
    fw_arr2.append(i)

In [38]:
n_dict_fw = dict(zip(fw_arr2, fw_arr))

In [39]:
#check
print(model_fw.wv.vectors[500])
print(n_dict_fw[500])

[ 0.45380005 -1.0902637  -0.29382357  0.66595083 -0.034418   -0.10894652
 -0.6283923  -0.47171608  1.1709592   0.62895566  0.933724   -0.651086
 -0.64669394  0.03058423 -0.6966853   0.17684942  0.9196023  -0.07306619
 -0.47049367 -0.06013809  0.30282485 -0.4528522   0.16792718  0.2860608
  0.6807774  -0.2482059  -0.23634876 -0.03607553 -0.16557486  0.73983693
 -0.09461167 -0.08649144]
[ 0.45380005 -1.0902637  -0.29382357  0.66595083 -0.034418   -0.10894652
 -0.6283923  -0.47171608  1.1709592   0.62895566  0.933724   -0.651086
 -0.64669394  0.03058423 -0.6966853   0.17684942  0.9196023  -0.07306619
 -0.47049367 -0.06013809  0.30282485 -0.4528522   0.16792718  0.2860608
  0.6807774  -0.2482059  -0.23634876 -0.03607553 -0.16557486  0.73983693
 -0.09461167 -0.08649144]


In [40]:
embedding_df_fr = pd.DataFrame.from_dict(n_dict, orient='index').reset_index()

In [41]:
col_list = []
for i in range (0,32):
    col_list.append("f" + str(i))
    
col_list.insert(0, "id")

embedding_df_fr.columns = col_list

In [42]:
list2 = col_list.copy()

In [43]:
list2.remove('id')

In [44]:
display(embedding_df_fr)

id        f0        f1  ...       f29       f30       f31
0        0 -0.117201  0.409337  ... -0.116992 -0.340265 -0.234395
1        1  0.385979  0.193495  ... -0.203750 -0.082388 -0.418740
2        2 -0.064782  0.108189  ... -0.131881 -0.021937 -0.411880
3        3 -0.076317  0.080320  ...  0.070868 -0.208381 -0.217727
4        4 -0.157010 -0.067280  ... -0.436911 -0.464190  0.119823
...    ...       ...       ...  ...       ...       ...       ...
1759  1759 -0.465017  0.038992  ... -0.452497  0.020703  0.267032
1760  1760 -0.548569 -0.663030  ... -0.061919 -0.928581 -0.535764
1761  1761 -0.906810  0.033241  ... -0.928349 -0.491973 -0.507083
1762  1762  0.015028 -0.035452  ... -0.223026 -0.738672 -0.188209
1763  1763 -0.601046  0.276007  ... -0.384039  0.597493 -0.633770

[1764 rows x 33 columns]

In [45]:
embedding_df_fw = pd.DataFrame.from_dict(n_dict_fw, orient='index').reset_index()

In [46]:
embedding_df_fw.columns = col_list

In [47]:
display(embedding_df_fw)

id        f0        f1        f2  ...       f28       f29       f30       f31
0      0  0.067297 -0.854068  0.022617  ... -0.371823  0.188064 -0.124672 -0.241982
1      1 -0.295130  0.114292  0.501191  ...  0.371669  0.384552 -0.238962 -0.196044
2      2 -0.358434 -0.205629  0.339129  ...  0.136582 -0.334811 -0.423009  0.106553
3      3 -0.451933 -0.177029  0.291225  ...  0.112211  0.705911 -0.422329  0.002886
4      4  0.437141 -0.972768 -0.245991  ...  0.029575  0.479984  0.134014 -0.039524
..   ...       ...       ...       ...  ...       ...       ...       ...       ...
527  527 -0.392587 -0.238111  0.183387  ...  0.173936 -0.415270 -0.611317  0.145590
528  528 -0.024774 -1.357596  0.678190  ...  0.019915 -0.845144 -0.936064 -0.240237
529  529 -0.011030 -0.714760  0.465864  ... -0.019027 -0.197488 -0.648804 -0.020970
530  530  0.057146 -0.850629  0.856476  ... -0.177590 -0.192106 -0.974852  0.262908
531  531  0.041574 -0.677608  0.651950  ... -0.316620  0.176945 -0.720299  0.246120

[532 rows x 33 columns]

In [48]:
embedding_df_fr.rename(columns={'id': 'new_id'}, inplace=True)

In [49]:
display(embedding_df_fr)

new_id        f0        f1  ...       f29       f30       f31
0          0 -0.117201  0.409337  ... -0.116992 -0.340265 -0.234395
1          1  0.385979  0.193495  ... -0.203750 -0.082388 -0.418740
2          2 -0.064782  0.108189  ... -0.131881 -0.021937 -0.411880
3          3 -0.076317  0.080320  ...  0.070868 -0.208381 -0.217727
4          4 -0.157010 -0.067280  ... -0.436911 -0.464190  0.119823
...      ...       ...       ...  ...       ...       ...       ...
1759    1759 -0.465017  0.038992  ... -0.452497  0.020703  0.267032
1760    1760 -0.548569 -0.663030  ... -0.061919 -0.928581 -0.535764
1761    1761 -0.906810  0.033241  ... -0.928349 -0.491973 -0.507083
1762    1762  0.015028 -0.035452  ... -0.223026 -0.738672 -0.188209
1763    1763 -0.601046  0.276007  ... -0.384039  0.597493 -0.633770

[1764 rows x 33 columns]

In [50]:
embedding_df_fw.rename(columns={'id': 'new_id'}, inplace=True)

In [51]:
display(embedding_df_fw)

new_id        f0        f1  ...       f29       f30       f31
0         0  0.067297 -0.854068  ...  0.188064 -0.124672 -0.241982
1         1 -0.295130  0.114292  ...  0.384552 -0.238962 -0.196044
2         2 -0.358434 -0.205629  ... -0.334811 -0.423009  0.106553
3         3 -0.451933 -0.177029  ...  0.705911 -0.422329  0.002886
4         4  0.437141 -0.972768  ...  0.479984  0.134014 -0.039524
..      ...       ...       ...  ...       ...       ...       ...
527     527 -0.392587 -0.238111  ... -0.415270 -0.611317  0.145590
528     528 -0.024774 -1.357596  ... -0.845144 -0.936064 -0.240237
529     529 -0.011030 -0.714760  ... -0.197488 -0.648804 -0.020970
530     530  0.057146 -0.850629  ... -0.192106 -0.974852  0.262908
531     531  0.041574 -0.677608  ...  0.176945 -0.720299  0.246120

[532 rows x 33 columns]

In [52]:
final_data = pd.concat((embedding_df_fr, embedding_df_fw))
final_data = final_data.groupby(final_data.index).mean()

In [53]:
display(final_data)

new_id        f0        f1  ...       f29       f30       f31
0          0 -0.024952 -0.222366  ...  0.035536 -0.232469 -0.238189
1          1  0.045425  0.153893  ...  0.090401 -0.160675 -0.307392
2          2 -0.211608 -0.048720  ... -0.233346 -0.222473 -0.152664
3          3 -0.264125 -0.048354  ...  0.388389 -0.315355 -0.107421
4          4  0.140065 -0.520024  ...  0.021537 -0.165088  0.040149
...      ...       ...       ...  ...       ...       ...       ...
1759    1759 -0.465017  0.038992  ... -0.452497  0.020703  0.267032
1760    1760 -0.548569 -0.663030  ... -0.061919 -0.928581 -0.535764
1761    1761 -0.906810  0.033241  ... -0.928349 -0.491973 -0.507083
1762    1762  0.015028 -0.035452  ... -0.223026 -0.738672 -0.188209
1763    1763 -0.601046  0.276007  ... -0.384039  0.597493 -0.633770

[1764 rows x 33 columns]

In [54]:
from sklearn.utils.extmath import softmax
emb_arr = final_data.drop(columns='new_id').to_numpy()

In [55]:
print(emb_arr)

[[-0.02495161 -0.22236559  0.22460371 ...  0.03553613 -0.23246884
  -0.23818867]
 [ 0.04542451  0.15389343  0.31368611 ...  0.09040064 -0.16067493
  -0.30739223]
 [-0.21160847 -0.04871997  0.23317026 ... -0.23334606 -0.22247305
  -0.15266366]
 ...
 [-0.90680993  0.03324139  0.09916678 ... -0.92834866 -0.4919726
  -0.50708282]
 [ 0.01502809 -0.03545205  0.16766597 ... -0.22302639 -0.73867244
  -0.18820898]
 [-0.60104603  0.27600667  0.72244292 ... -0.38403946  0.59749275
  -0.63376999]]


In [56]:
s_arr = softmax(emb_arr)

In [57]:
print(s_arr)

[[0.03143081 0.0258     0.04034001 ... 0.03339066 0.02554065 0.02539498]
 [0.03313184 0.03692776 0.04332614 ... 0.034656   0.0269611  0.02328194]
 [0.02847632 0.03351394 0.04442719 ... 0.027864   0.02816861 0.03020531]
 ...
 [0.01287245 0.03295493 0.03520071 ... 0.01259816 0.0194905  0.0191982 ]
 [0.02996517 0.02849007 0.03490652 ... 0.02361734 0.01410226 0.02445412]
 [0.01505615 0.03619204 0.05655849 ... 0.01870504 0.04991518 0.01457143]]


In [58]:
softmax_df = pd.DataFrame(s_arr, columns=list2)
display(softmax_df)

f0        f1        f2  ...       f29       f30       f31
0     0.031431  0.025800  0.040340  ...  0.033391  0.025541  0.025395
1     0.033132  0.036928  0.043326  ...  0.034656  0.026961  0.023282
2     0.028476  0.033514  0.044427  ...  0.027864  0.028169  0.030205
3     0.023548  0.029219  0.038267  ...  0.045221  0.022372  0.027543
4     0.035047  0.018112  0.025964  ...  0.031129  0.025830  0.031714
...        ...       ...       ...  ...       ...       ...       ...
1759  0.017551  0.029053  0.017952  ...  0.017772  0.028526  0.036494
1760  0.018301  0.016321  0.037494  ...  0.029773  0.012515  0.018537
1761  0.012872  0.032955  0.035201  ...  0.012598  0.019490  0.019198
1762  0.029965  0.028490  0.034907  ...  0.023617  0.014102  0.024454
1763  0.015056  0.036192  0.056558  ...  0.018705  0.049915  0.014571

[1764 rows x 32 columns]

In [59]:
id_value = final_data['new_id']
print(id_value)

0          0
1          1
2          2
3          3
4          4
        ... 
1759    1759
1760    1760
1761    1761
1762    1762
1763    1763
Name: new_id, Length: 1764, dtype: int64


In [60]:
softmax_df.set_index(keys=id_value, inplace=True)

In [61]:
display(softmax_df)

f0        f1        f2  ...       f29       f30       f31
new_id                                ...                              
0       0.031431  0.025800  0.040340  ...  0.033391  0.025541  0.025395
1       0.033132  0.036928  0.043326  ...  0.034656  0.026961  0.023282
2       0.028476  0.033514  0.044427  ...  0.027864  0.028169  0.030205
3       0.023548  0.029219  0.038267  ...  0.045221  0.022372  0.027543
4       0.035047  0.018112  0.025964  ...  0.031129  0.025830  0.031714
...          ...       ...       ...  ...       ...       ...       ...
1759    0.017551  0.029053  0.017952  ...  0.017772  0.028526  0.036494
1760    0.018301  0.016321  0.037494  ...  0.029773  0.012515  0.018537
1761    0.012872  0.032955  0.035201  ...  0.012598  0.019490  0.019198
1762    0.029965  0.028490  0.034907  ...  0.023617  0.014102  0.024454
1763    0.015056  0.036192  0.056558  ...  0.018705  0.049915  0.014571

[1764 rows x 32 columns]

In [62]:
softmax_df['new_id'] = softmax_df.index

In [63]:
softmax_df = softmax_df[ ['new_id'] + [ col for col in softmax_df.columns if col != 'new_id' ] ]
softmax_df.index.name = None

In [64]:
display(softmax_df)

new_id        f0        f1  ...       f29       f30       f31
0          0  0.031431  0.025800  ...  0.033391  0.025541  0.025395
1          1  0.033132  0.036928  ...  0.034656  0.026961  0.023282
2          2  0.028476  0.033514  ...  0.027864  0.028169  0.030205
3          3  0.023548  0.029219  ...  0.045221  0.022372  0.027543
4          4  0.035047  0.018112  ...  0.031129  0.025830  0.031714
...      ...       ...       ...  ...       ...       ...       ...
1759    1759  0.017551  0.029053  ...  0.017772  0.028526  0.036494
1760    1760  0.018301  0.016321  ...  0.029773  0.012515  0.018537
1761    1761  0.012872  0.032955  ...  0.012598  0.019490  0.019198
1762    1762  0.029965  0.028490  ...  0.023617  0.014102  0.024454
1763    1763  0.015056  0.036192  ...  0.018705  0.049915  0.014571

[1764 rows x 33 columns]

In [65]:
merged_final_data = pd.merge(nodes_data, softmax_df, how='outer', on='new_id')

In [66]:
merged_final_data = merged_final_data.dropna()

In [67]:
display(merged_final_data)

new_id  class       tw_id  ...       f29       f30       f31
0          0  False   461277906  ...  0.033391  0.025541  0.025395
1          1  False   808280162  ...  0.034656  0.026961  0.023282
2          2  False  1575510320  ...  0.027864  0.028169  0.030205
3          3  False  2449235599  ...  0.045221  0.022372  0.027543
4          4  False  1113769100  ...  0.031129  0.025830  0.031714
...      ...    ...         ...  ...       ...       ...       ...
1759    1759   True   355303278  ...  0.017772  0.028526  0.036494
1760    1760   True   288948026  ...  0.029773  0.012515  0.018537
1761    1761   True  2183080705  ...  0.012598  0.019490  0.019198
1762    1762   True   859364185  ...  0.023617  0.014102  0.024454
1763    1763   True  2423734735  ...  0.018705  0.049915  0.014571

[1764 rows x 47 columns]

In [68]:
label = merged_final_data['class']
merged_final_data = merged_final_data.drop(columns='class')
merged_final_data.insert(loc=46, column='label', value=label)
merged_final_data = merged_final_data.drop(columns=['new_id', 'tw_id'])

In [69]:
display(merged_final_data)

statuses_count  followers_count  friends_count  ...       f30       f31  label
0              10728           379139           2949  ...  0.025541  0.025395  False
1             141143            26048            337  ...  0.026961  0.023282  False
2             180426           120558         108607  ...  0.028169  0.030205  False
3              13046            26258             18  ...  0.022372  0.027543  False
4              72434            75208          78570  ...  0.025830  0.031714  False
...              ...              ...            ...  ...       ...       ...    ...
1759           29159             1679           1619  ...  0.028526  0.036494   True
1760           12138              903            692  ...  0.012515  0.018537   True
1761           16011             1289           4149  ...  0.019490  0.019198   True
1762           22361              896            305  ...  0.014102  0.024454   True
1763           57268              814            603  ...  0.049915  0.014571   True

[1764 rows x 45 columns]

In [70]:
X = merged_final_data.iloc[:,:-1]

y = merged_final_data.iloc[:,-1]

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [73]:
scaled_df = pd.DataFrame(X_train)
display(scaled_df)

0         1         2   ...        41        42        43
0     0.792197 -0.173502 -0.173711  ... -0.292134 -0.187979 -0.341428
1     0.607011  0.063928  0.074662  ... -0.312873  0.712935  0.106385
2    -0.202126 -0.173519 -0.169751  ... -0.107753 -0.255696 -1.022274
3    -0.550329 -0.173604 -0.185657  ... -0.422630 -0.706801  1.774522
4    -0.100101 -0.148639 -0.165939  ... -0.091680  0.590892  4.013870
...        ...       ...       ...  ...       ...       ...       ...
1406 -0.535493 -0.149839 -0.178632  ...  0.843909  0.805881  0.557486
1407 -0.426375 -0.167909 -0.088197  ...  0.420812 -0.878161 -0.722298
1408  0.977516  0.165395 -0.185306  ...  0.614591  1.352885 -0.125881
1409 -0.534494 -0.163845  0.496415  ... -0.638669 -0.775435  1.257487
1410 -0.473134 -0.128548 -0.183191  ...  0.030289  0.332229 -0.111276

[1411 rows x 44 columns]

In [74]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=20, random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [75]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[173  25]
 [ 29 126]]
              precision    recall  f1-score   support

       False       0.86      0.87      0.86       198
        True       0.83      0.81      0.82       155

    accuracy                           0.85       353
   macro avg       0.85      0.84      0.84       353
weighted avg       0.85      0.85      0.85       353

0.8470254957507082


In [76]:
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier(random_state=42)

param_grid = { 
    'n_estimators': [50, 150, 250],
    'max_features': ['auto', 'sqrt',  0.5, 1.0],
    'min_samples_split' : [2, 4, 6],
}


In [77]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv=5)
CV_rfc.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=42,
                                  

In [78]:
CV_rfc.best_params_

{'max_features': 0.5, 'min_samples_split': 4, 'n_estimators': 250}

In [79]:
rfc1=RandomForestClassifier(random_state=42, max_features=0.5, n_estimators= 250, min_samples_split=4)

In [80]:
rfc1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=0.5,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, n_estimators=250,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [81]:
pred = rfc1.predict(X_test)

In [82]:
print("Accuracy for Random Forest on CV data: ",accuracy_score(y_test,pred))

Accuracy for Random Forest on CV data:  0.8980169971671388


In [83]:
pd.set_option('display.max_rows', 100)

In [84]:
feature_imp = pd.Series(clf.feature_importances_,index=X.columns).sort_values(ascending=False)
feature_imp

statuses_count          0.126474
followers_count         0.053841
f9                      0.049160
favourites_count        0.043962
f19                     0.041526
f16                     0.040384
f10                     0.034688
f15                     0.031631
f23                     0.030180
f1                      0.029430
f3                      0.028554
listed_count            0.028484
f7                      0.027618
f14                     0.026528
f31                     0.023598
f4                      0.022685
f20                     0.020983
f8                      0.020019
f17                     0.019476
f26                     0.018673
f5                      0.018490
f27                     0.018073
friends_count           0.018069
f24                     0.017982
f0                      0.017698
f28                     0.017565
f12                     0.017193
f18                     0.017057
f21                     0.016482
f6                      0.016416
f13       

In [93]:
from sklearn.feature_selection import SelectFromModel
feat_sel = SelectFromModel(clf,threshold=0.0144)
feat_sel.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=20, n_jobs=None,
                                                 oob_score=False,


In [94]:
X_imp_train = feat_sel.transform(X_train)
X_imp_test = feat_sel.transform(X_test)

In [95]:
CV_rfc_imp = GridSearchCV(estimator=rfc, param_grid=param_grid, cv=5)
CV_rfc_imp.fit(X_imp_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=42,
                                  

In [96]:
CV_rfc_imp.best_params_

{'max_features': 0.5, 'min_samples_split': 6, 'n_estimators': 150}

In [97]:
rfc_imp = RandomForestClassifier(random_state=42, max_features=0.5, n_estimators=150, min_samples_split=6)

In [98]:
rfc_imp.fit(X_imp_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=0.5,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=6,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [99]:
pred_imp = rfc_imp.predict(X_imp_test)

In [100]:
print("Accuracy for Random Forest on CV data: ",accuracy_score(y_test,pred_imp))

Accuracy for Random Forest on CV data:  0.8923512747875354
